/** @type {import('tailwindcss').Config} */
// Tema "Minimal Editorial" portado del mockup de Stitch (monocromático, Noto Serif).
// borderRadius default de Tailwind a propósito (la página usa rounded-[20px]/[100px]
// como valores arbitrarios; overridear `full` rompería los círculos).
module.exports = {
  content: ['./index.html', './secciones/*.html', './assets/js/*.js'],
  theme: {
    extend: {
      colors: {
        'inverse-primary': '#c6c6c6',
        'surface-bright': '#f9f9f9',
        'on-secondary': '#ffffff',
        'on-primary-container': '#848484',
        error: '#ba1a1a',
        'on-primary-fixed': '#1b1b1b',
        tertiary: '#000000',
        'on-surface': '#1a1c1c',
        'on-secondary-fixed-variant': '#464747',
        'on-error-container': '#93000a',
        'on-secondary-container': '#646464',
        'surface-container': '#eeeeee',
        'primary-fixed': '#e2e2e2',
        'on-tertiary-container': '#838484',
        surface: '#f9f9f9',
        'secondary-fixed-dim': '#c7c6c6',
        'secondary-fixed': '#e3e2e2',
        'error-container': '#ffdad6',
        'on-tertiary': '#ffffff',
        'outline-variant': '#cfc4c5',
        'on-surface-variant': '#4c4546',
        'secondary-container': '#e3e2e2',
        'surface-container-high': '#e8e8e8',
        'surface-dim': '#dadada',
        'surface-variant': '#e2e2e2',
        'on-tertiary-fixed': '#1a1c1c',
        'surface-tint': '#5e5e5e',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed-variant': '#454747',
        'on-error': '#ffffff',
        'surface-container-low': '#f3f3f4',
        secondary: '#5e5e5e',
        'tertiary-container': '#1a1c1c',
        primary: '#000000',
        'on-primary': '#ffffff',
        'on-background': '#1a1c1c',
        outline: '#7e7576',
        'surface-container-highest': '#e2e2e2',
        background: '#f9f9f9',
        'inverse-surface': '#2f3131',
        'primary-fixed-dim': '#c6c6c6',
        'on-primary-fixed-variant': '#474747',
        'on-secondary-fixed': '#1b1c1c',
        'tertiary-fixed': '#e2e2e2',
        'tertiary-fixed-dim': '#c6c6c7',
        'primary-container': '#1b1b1b',
        'inverse-on-surface': '#f0f1f1',
        // Home oscuro (Aurora). Nombres propios para no pisar los tokens claros de las subpáginas.
        ink: '#0a0a0a',
        'ink-soft': '#131313',
        'cool-violet': '#9d85ff',
        'violet-accent': '#c5c0ff',
        'violet-strong': '#8981ff',
        'on-violet': '#1e0090',
        ember: '#f2994a',
        'error-soft': '#ff6b6b',
      },
      spacing: {
        unit: '8px',
        gutter: '32px',
        'margin-page': '64px',
        'section-padding': '128px',
      },
      maxWidth: {
        container: '1200px',
      },
      fontFamily: {
        sans: ['Manrope', 'system-ui', '-apple-system', 'sans-serif'],
        serif: ['Noto Serif', 'Georgia', 'Times New Roman', 'serif'],
        // Home oscuro (Aurora)
        garamond: ['EB Garamond', 'Georgia', 'serif'],
        grotesk: ['Hanken Grotesk', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['13px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
